// ISO Timestamp: 2025-11-24T20:00:00Z
/**
 * AIVS Invoice Checker – Root Backend (pdfjs + compliance engine)
 */

import express from "express";
import cors from "cors";
import multer from "multer";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { extractInvoice } from "./pdf_extract.js";              // UPDATED
import { runComplianceChecks } from "./compliance_engine.js";   // UPDATED

import Mailjet from "node-mailjet";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { Document, Packer, Paragraph, TextRun } from "docx";

/* -----------------------------------------------------------
   PATH + APP SETUP
----------------------------------------------------------- */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

/* -----------------------------------------------------------
   STATIC FRONTEND DIRECTORY
----------------------------------------------------------- */
app.use(express.static(path.join(__dirname, "public")));

/* -----------------------------------------------------------
   ⭐ FIX FOR 502 – SERVE FRONTEND ON GET "/" 
----------------------------------------------------------- */
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});
/* -----------------------------------------------------------
   END FIX
----------------------------------------------------------- */

/* -----------------------------------------------------------
   UPLOAD + GENERATED FILE DIRECTORIES
----------------------------------------------------------- */
const uploadDir = path.join(__dirname, "uploads");
const generatedDir = path.join(__dirname, "generated");

if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

const upload = multer({
  dest: uploadDir,
  limits: { fileSize: 25 * 1024 * 1024 }
});

/* -----------------------------------------------------------
   FOOTER TEXT
----------------------------------------------------------- */
const FOOTER_TEXT = `
© AIVS Software Limited 2025 · All rights reserved.
This CIS/VAT report is generated by the AIVS Compliance Checker for internal advisory use.
It does not constitute accounting, tax, or legal advice.
Prepared for internal management review only · Not for external distribution.
`;

/* -----------------------------------------------------------
   PDF GENERATOR
----------------------------------------------------------- */
async function generatePDF(aiReply, timestamp) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  let y = 800;

  const write = (text) => {
    page.drawText(text, { x: 40, y, size: 12, font });
    y -= 18;
  };

  write("AIVS CIS/VAT Compliance Report");
  write(`Generated: ${timestamp}`);
  write("");

  write(`VAT Check: ${aiReply.vat_check}`);
  write(`CIS Check: ${aiReply.cis_check}`);
  write(`Required Wording: ${aiReply.required_wording}`);
  write("");

  write("Summary:");
  aiReply.summary.split("\n").forEach((line) => write(line));

  write("");
  write(FOOTER_TEXT);

  return await pdfDoc.save();
}

/* -----------------------------------------------------------
   DOCX GENERATOR
----------------------------------------------------------- */
async function generateDOCX(aiReply, timestamp) {
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({
          children: [new TextRun({ text: "AIVS CIS/VAT Compliance Report", bold: true, size: 28 })]
        }),
        new Paragraph({ text: `Generated: ${timestamp}` }),
        new Paragraph(""),
        new Paragraph({ text: `VAT Check: ${aiReply.vat_check}` }),
        new Paragraph({ text: `CIS Check: ${aiReply.cis_check}` }),
        new Paragraph({ text: `Required Wording: ${aiReply.required_wording}` }),
        new Paragraph(""),
        new Paragraph({ text: "Summary:" }),
        ...aiReply.summary.split("\n").map((line) => new Paragraph(line)),
        new Paragraph(""),
        new Paragraph({ text: FOOTER_TEXT, size: 16 })
      ]
    }]
  });

  return await Packer.toBuffer(doc);
}

/* -----------------------------------------------------------
   MAILJET EMAIL SENDER
----------------------------------------------------------- */
const mailjet = Mailjet.apiConnect(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
);

export async function sendReportEmail(toEmail, ccList, docPath, pdfPath, timestamp) {
  try {
    const attachments = [];

    if (fs.existsSync(docPath)) {
      attachments.push({
        ContentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        Filename: path.basename(docPath),
        Base64Content: fs.readFileSync(docPath, "base64")
      });
    }

    if (fs.existsSync(pdfPath)) {
      attachments.push({
        ContentType: "application/pdf",
        Filename: path.basename(pdfPath),
        Base64Content: fs.readFileSync(pdfPath, "base64")
      });
    }

    const recipients = [];
    if (toEmail) recipients.push({ Email: toEmail });
    ccList.forEach((e) => { if (e && e.trim()) recipients.push({ Email: e.trim() }); });

    if (recipients.length === 0) return;

    await mailjet.post("send", { version: "v3.1" }).request({
      Messages: [{
        From: { Email: "noreply@securemaildrop.uk", Name: "AIVS Compliance Checker" },
        To: recipients,
        Subject: "AIVS CIS/VAT Compliance Report",
        HTMLPart: `<h3>AIVS CIS/VAT Compliance Report</h3><p>Generated: ${timestamp}</p>`,
        Attachments: attachments
      }]
    });

  } catch (err) {
    console.error("❌ Email sending error:", err.message);
  }
}

/* -----------------------------------------------------------
   MAIN ROUTE
----------------------------------------------------------- */
app.post("/check_invoice", upload.single("file"), async (req, res) => {
  try {
    if (!req.file)
      return res.status(400).json({ error: "No file uploaded" });

    const filePath = req.file.path;
    const timestamp = new Date().toISOString();

    const docResult = await extractInvoice(filePath);
    if (docResult.status !== "ok")
      return res.json({ success: false, error: docResult.error });

    const aiReply = runComplianceChecks(docResult.extracted.text);

    const docBuffer = await generateDOCX(aiReply, timestamp);
    const pdfBuffer = await generatePDF(aiReply, timestamp);

    const safeTime = timestamp.replace(/[:]/g, "-");
    const docPath = path.join(generatedDir, `report_${safeTime}.docx`);
    const pdfPath = path.join(generatedDir, `report_${safeTime}.pdf`);

    fs.writeFileSync(docPath, docBuffer);
    fs.writeFileSync(pdfPath, pdfBuffer);

    return res.json({
      success: true,
      aiReply,
      timestamp
    });

  } catch (err) {
    console.error("❌ /check_invoice ERROR:", err);
    return res.status(500).json({ error: err.message });
  }
});

/* -----------------------------------------------------------
   START SERVER
----------------------------------------------------------- */
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`🚀 AIVS Root Invoice Checker running on port ${PORT}`);
});
