// ISO Timestamp: 2025-11-24T18:00:00Z
/**
 * check_invoice.js – AIVS Route Handler
 * Dropzone → Docling → Compliance Engine → HTML Preview → PDF/DOCX → Email
 */

import express from "express";
import multer from "multer";
import fs from "fs";
import path from "path";

import { extractInvoice } from "../../docling_extract.js";
import { runComplianceChecks } from "../../compliance_engine.js";
import { sendReportEmail } from "../../server.js";

import { PDFDocument, StandardFonts } from "pdf-lib";
import { Document, Packer, Paragraph, TextRun } from "docx";

const router = express.Router();

/* -----------------------------------------------------------
   Upload directory
----------------------------------------------------------- */
const uploadDir = "/opt/render/project/src/uploads";
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

const upload = multer({
  dest: uploadDir,
  limits: { fileSize: 25 * 1024 * 1024 }
});

/* -----------------------------------------------------------
   Report directory
----------------------------------------------------------- */
const generatedDir = "/opt/render/project/src/generated";
if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

/* -----------------------------------------------------------
   FOOTER (PDF & DOCX only)
----------------------------------------------------------- */
const FOOTER_TEXT = `
© AIVS Software Limited 2025 · All rights reserved.
Generated by the AIVS CIS/VAT Compliance Checker for internal advisory use.
This report does not constitute professional accounting or legal advice.
Prepared for internal management review only · Not for external distribution.
`;

/* -----------------------------------------------------------
   PDF GENERATOR (no invoice preview inside)
----------------------------------------------------------- */
async function generatePDF(aiReply, timestamp) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  let y = 800;

  const write = (line) => {
    page.drawText(line, { x: 40, y, size: 12, font });
    y -= 18;
  };

  write("AIVS CIS/VAT Compliance Report");
  write(`Generated: ${timestamp}`);
  write("");
  write(`VAT Check: ${aiReply.vat_check}`);
  write(`CIS Check: ${aiReply.cis_check}`);
  write(`Required Wording: ${aiReply.required_wording}`);
  write("");
  write("Summary:");
  aiReply.summary.split("\n").forEach(write);
  write("");
  write(FOOTER_TEXT);

  return await pdfDoc.save();
}

/* -----------------------------------------------------------
   DOCX GENERATOR (no invoice preview inside)
----------------------------------------------------------- */
async function generateDOCX(aiReply, timestamp) {
  const children = [
    new Paragraph({
      children: [new TextRun({ text: "AIVS CIS/VAT Compliance Report", bold: true, size: 28 })]
    }),
    new Paragraph(`Generated: ${timestamp}`),
    new Paragraph(""),
    new Paragraph(`VAT Check: ${aiReply.vat_check}`),
    new Paragraph(`CIS Check: ${aiReply.cis_check}`),
    new Paragraph(`Required Wording: ${aiReply.required_wording}`),
    new Paragraph(""),
    new Paragraph("Summary:"),
    ...aiReply.summary.split("\n").map((line) => new Paragraph(line)),
    new Paragraph(""),
    new Paragraph({ text: FOOTER_TEXT, size: 16 })
  ];

  const doc = new Document({ sections: [{ children }] });
  return await Packer.toBuffer(doc);
}

/* -----------------------------------------------------------
   MAIN ROUTE – /check_invoice
----------------------------------------------------------- */
router.post("/check_invoice", upload.single("file"), async (req, res) => {
  const timestamp = new Date().toISOString();

  try {
    if (!req.file) {
      return res.json({
        success: false,
        html: `<div style="color:#c0392b;">❌ No file uploaded.</div>`
      });
    }

    const {
      vatCategory = "",
      endUserConfirmed = "",
      cisRate = "",
      partyRole = "",
      userEmail = "",
      emailCopy1 = "",
      emailCopy2 = ""
    } = req.body;

    /* ----------------------------------------------------------
       1. Docling extract
    ---------------------------------------------------------- */
    const docResult = await extractInvoice(req.file.path);

    if (docResult.status !== "ok") {
      return res.json({
        success: false,
        html: `<div style="color:#c0392b;">
               ❌ PDF unreadable<br>${docResult.error || docResult.message}
               </div>`
      });
    }

    /* ----------------------------------------------------------
       2. Compliance Engine (CIS/VAT logic)
    ---------------------------------------------------------- */
    const aiReply = runComplianceChecks(docResult.extracted);

    /* ----------------------------------------------------------
       3. Build HTML preview (screen only)
    ---------------------------------------------------------- */
    const html = `
      <div style="padding:12px;">
        <h3 style="color:#4e65ac;font-size:18px;font-weight:700;">AIVS CIS/VAT Compliance Report</h3>

        <p><strong>VAT Check:</strong><br>${aiReply.vat_check}</p>
        <p><strong>CIS Check:</strong><br>${aiReply.cis_check}</p>
        <p><strong>Required Wording:</strong><br>${aiReply.required_wording}</p>

        <p><strong>Summary:</strong><br>${aiReply.summary.replace(/\n/g, "<br>")}</p>

        <h4 style="color:#4e65ac;margin-top:20px;">Draft Corrected Invoice (Screen Only)</h4>
        <div style="border:1px solid #ddd;padding:10px;background:#fafafa;">
          ${aiReply.corrected_invoice}
        </div>

        <div style="margin-top:20px;color:#999;font-size:12px;">
          Generated: ${timestamp}
        </div>
      </div>
    `;

    /* ----------------------------------------------------------
       4. Generate PDF/DOCX (no invoice preview)
    ---------------------------------------------------------- */
    const docBuf = await generateDOCX(aiReply, timestamp);
    const pdfBuf = await generatePDF(aiReply, timestamp);

    const docPath = path.join(generatedDir, `report_${timestamp}.docx`.replace(/[:]/g, "-"));
    const pdfPath = path.join(generatedDir, `report_${timestamp}.pdf`.replace(/[:]/g, "-"));

    fs.writeFileSync(docPath, docBuf);
    fs.writeFileSync(pdfPath, pdfBuf);

    /* ----------------------------------------------------------
       5. Auto-email if fields provided
    ---------------------------------------------------------- */
    if (userEmail || emailCopy1 || emailCopy2) {
      await sendReportEmail(userEmail, [emailCopy1, emailCopy2], docPath, pdfPath, timestamp);
    }

    /* ----------------------------------------------------------
       6. Return HTML to frontend
    ---------------------------------------------------------- */
    return res.json({ success: true, html, timestamp });

  } catch (err) {
    console.error("❌ check_invoice.js error:", err);
    return res.json({
      success: false,
      html: `<div style="color:#c0392b;">
             Server error:<br>${err.message}
             </div>`
    });
  }
});

export default router;
